[stage-two]
round-of-16 = [ "Poland", "Croatia", "England", "Belgium", "Germany", "Sweden", "France", "Russia",]
semi-final = [ "England", "Germany",]
quarter-final = [ "Croatia", "England", "Germany", "Russia",]
[info]
user = "KNergaard"
[stage-one]
results = [ [ "B", "B", "B", "B", "H", "H",], [ "H", "H", "H", "B", "B", "H",], [ "H", "H", "H", "H", "B", "B",], [ "H", "H", "U", "U", "B", "B",], [ "U", "B", "H", "H", "U", "H",], [ "U", "U", "B", "H", "H", "B",],]
third-places = [ "Italy", "Slovakia", "Romania", "Ukraine",]
winners = [ [ "France", "Switzerland",], [ "England", "Russia",], [ "Germany", "Poland",], [ "Croatia", "Spain",], [ "Sweden", "Belgium",], [ "Portugal", "Iceland",],]
[finals]
final = "Germany"
