name = "UEFA Euro 2016 France"
type = "uefa-euro"
groups = [
    ["Albania",     "France",           "Romania",  "Switzerland"],
    ["England",     "Russia",           "Slovakia", "Wales"],
    ["Germany",     "Northern Ireland", "Poland",   "Ukraine"],
    ["Croatia",     "Czech Republic",   "Spain",    "Turkey"],
    ["Belgium",     "Italy",            "Ireland",  "Sweden"],
    ["Austria",     "Hungary",          "Iceland",  "Portugal"],
]