[finals]
final = "Spain"
[info]
user = "AGiailoglou"
[stage-one]
results = [ [ "b", "b", "b", "b", "h", "h",], [ "b", "h", "h", "b", "b", "h",], [ "h", "b", "h", "u", "b", "b",], [ "b", "h", "b", "b", "b", "b",], [ "b", "b", "h", "u", "h", "h",], [ "u", "b", "b", "h", "h", "b",],]
winners = [ [ "France", "Switzerland",], [ "Russia", "England",], [ "Germany", "Ukraine",], [ "Spain", "Czech Republic",], [ "Italy", "Sweden",], [ "Portugal", "Iceland",],]
third-places = [ "Romania", "Slovakia", "Belgium", "Croatia",]
[stage-two]
round-of-16 = [ "Ukraine", "Spain", "Russia", "Portugal", "Germany", "Italy", "France", "England",]
semi-final = [ "Spain", "Germany",]
quarter-final = [ "Spain", "Portugal", "Germany", "France",]
