[finals]
final = "France"
[stage-two]
quarter-final = [ "Spain", "England", "Germany", "France",]
semi-final = [ "Spain", "France",]
round-of-16 = [ "Poland", "Spain", "England", "Austria", "Germany", "Belgium", "France", "Portugal",]
[stage-one]
results = [ [ "b", "u", "b", "b", "h", "h",], [ "h", "u", "h", "b", "b", "h",], [ "h", "u", "h", "h", "b", "b",], [ "h", "h", "b", "h", "u", "b",], [ "u", "b", "h", "h", "b", "h",], [ "h", "b", "h", "h", "b", "b",],]
winners = [ [ "France", "Romania",], [ "England", "Russia",], [ "Germany", "Poland",], [ "Spain", "Croatia",], [ "Belgium", "Sweden",], [ "Austria", "Portugal",],]
third-places = [ "Turkey", "Switzerland", "Italy", "Ukraine",]
[info]
user = "AGilje"
