[stage-one]
results = [ [ "b", "u", "h", "u", "h", "h",], [ "u", "b", "u", "h", "b", "b",], [ "h", "h", "u", "b", "b", "b",], [ "u", "h", "h", "h", "b", "b",], [ "b", "u", "h", "b", "b", "b",], [ "b", "u", "b", "u", "u", "u",],]
third-places = [ "Ireland", "Slovakia", "Northern Ireland", "Portugal",]
winners = [ [ "France", "Switzerland",], [ "Wales", "England",], [ "Germany", "Poland",], [ "Croatia", "Spain",], [ "Italy", "Belgium",], [ "Hungary", "Iceland",],]
[finals]
final = "-"
[stage-two]
quarter-final = [ "Portugal", "-", "-", "-",]
semi-final = [ "-", "-",]
round-of-16 = [ "Poland", "Portugal", "Wales", "Belgium", "Germany", "Italy", "France", "Iceland",]
[info]
user = "actual"
