[stage-two]
semi-final = [ "Spain", "Belgium",]
quarter-final = [ "Spain", "England", "Belgium", "France",]
round-of-16 = [ "Poland", "Spain", "England", "Portugal", "Germany", "Belgium", "France", "Austria",]
[finals]
final = "Belgium"
[stage-one]
winners = [ [ "France", "Switzerland",], [ "England", "Russia",], [ "Germany", "Poland",], [ "Spain", "Czech Republic",], [ "Belgium", "Italy",], [ "Portugal", "Austria",],]
third-places = [ "Sweden", "Ukraine", "Iceland", "Croatia",]
results = [ [ "B", "B", "H", "B", "H", "H",], [ "H", "U", "H", "B", "B", "H",], [ "H", "H", "H", "H", "B", "B",], [ "B", "H", "B", "B", "B", "B",], [ "H", "B", "H", "B", "B", "H",], [ "H", "B", "H", "H", "H", "B",],]
[info]
user = "EHaugnes"
